### ISSUE TITLE
群组聊天的支持

### ISSUE THREAD

**Issue by panjunyong** [Terry-Mao/gopush-cluster#14]
需求场景是：聊天室中发一条消息，只需要发一条就行了，这样也减少消息发送和存储方面的消耗。

Terry Mao答复： 聊天室的场景，类似topic了，我们后期会考虑支持这种协议。这边可能会叫 group，类似QQ群的概念

**Comment by Terry-Mao** [comment]
目前goim已经支持：github.com/Terry-Mao/goim
