### ISSUE TITLE
/msg/get 获取离线消息这个接口其实可以省略

### ISSUE THREAD

**Issue by newjueqi** [Terry-Mao/gopush-cluster#21]
其实客户端离线消息的获取，不需要客户端通过url来获取的。
       只要在客户端订阅的时，把最后的消息id作为订阅参数传过来，服务器立刻推送离线消息给客户端就好了，这样客户端就不需要维护太多的离线消息逻辑，客户端的工作量

**Comment by Terry-Mao** [comment]
你说的意思我明白，后来当时想了下，还是用的第一种方式
