### ISSUE TITLE
楼主能不能做一个docker版本供测试

### ISSUE THREAD

**Issue by alexwhen** [Terry-Mao/gopush-cluster#29]
楼主能不能做一个docker版本供测试？？

**Comment by Terry-Mao** [comment]
好建议，我先熟悉docker的使用

**Comment by yuwenzhenyu** [comment]
搞个docker好一些，现在在用windows，不方便使用有docker的话直接用boot2docker 搞起了

**Comment by 2guotou** [comment]
nice advice, Teacher Mao,hurry up

On Sun, Jan 25, 2015 at 5:17 PM, yuwenzhenyu <notifications@github.com>
wrote:

> 搞个docker好一些，现在在用windows，不方便使用有docker的话直接用boot2docker 搞起了
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Terry-Mao/gopush-cluster/issues/29#issuecomment-71361942>
> .
>



-- 
来自  丘人`刘东阳
From Nuttycase`Sungelina

**Comment by litrue** [comment]
docker镜像有谱了吗？

**Comment by Terry-Mao** [comment]
尽快，最近挺忙。。。

**Comment by vyloy** [comment]
有了吗？

**Comment by alexwhen** [comment]
本来我打算弄一个，但看了一下，按docker理念分离应用和数据，文档还不够

**Comment by Terry-Mao** [comment]
分离数据是指的是，message存储的离线消息么

**Comment by alexwhen** [comment]
@Terry-Mao 配置太分散，这里要创建好多个容器，新加节点，如何自动加入等等，可能考虑得有点多，尽量自动化

**Comment by alexwhen** [comment]
zookeeper,redis,message,comet,mysql,web,日志分析，至少7个容器镜像，我先弄一个简单版本的试试看

**Comment by Terry-Mao** [comment]
辛苦。。
