### ISSUE TITLE
请问目前tcp协议是否可以发消息？看了代码貌似只处理了sub命令和心跳。

### ISSUE THREAD

**Issue by chenjw1985** [Terry-Mao/gopush-cluster#30]
你好！
请问目前是不是只能通过curl命令发送信息，tcp客户端怎么发？

**Comment by Terry-Mao** [comment]
tcp客户端可以看wiki 下的 sdk 文档

**Comment by Terry-Mao** [comment]
tcp的，目前可以使用最新的goim ，支持上行命令，性能和架构比gopush更简单
github.com/Terry-Mao/goim
