### ISSUE TITLE
关于gopush-cluster的使用

### ISSUE THREAD

**Issue by shenshouer** [Terry-Mao/gopush-cluster#31]
你好！
我看了下您的这个框架，感觉很好！
只是关于此系统的文档描述太少，像特性中所描述的功能，具体使用例子都没有，这个可能很多想使用这个框架的人很大的阻力。建议开通一个QQ群，方便大家一起交流，大家齐心合力来发展这个，并完善文档，方便后来人！

**Comment by aszxqw** [comment]
恩同建议开通一个QQ群。
而且问一下，本项目的并发测试如何，单机能承受的并发连接数量是多少呢？

**Comment by Terry-Mao** [comment]
有QQ群：188279200

**Comment by Terry-Mao** [comment]
使用例子，全部在wiki目录下

**Comment by dtxlink** [comment]
太给力了
