### ISSUE TITLE
websocket如何使用

### ISSUE THREAD

**Issue by oliver258** [Terry-Mao/gopush-cluster#33]
在6968端口上直接发送
"*4\r\n$3\r\nsub\r\n$9\r\nTerry-Mao\r\n$2\r\n30\r\n$5\r\n1.0.4\r\n"
这样的数据总是返回400 Bad Request。
请问到底怎么发送数据？

**Comment by Terry-Mao** [comment]
这个，应该是连接错端口了吧。。。
