### ISSUE TITLE
gopush-cluster-javascript-sdk在index.html页websocket 403错误

### ISSUE THREAD

**Issue by liudanking** [Terry-Mao/gopush-cluster#34]
在学习lz的这套框架。搭建起来运行正常。准备用js sdk测试一下websocket。遇到一个问题：
WebSocket connection to 'ws://localhost:6968/sub?key=Lanfei&heartbeat=60' failed: Error during WebSocket handshake: Unexpected response code: 403

应该怎么解决？

**Comment by Terry-Mao** [comment]
websocket协议还是老的，维护者应该很久没升级了。

**Comment by liudanking** [comment]
请问应该怎样quick fix呢？

**Comment by Terry-Mao** [comment]
QQ群：188279200
