### ISSUE TITLE
Redis.Dial()报错,没有解析到正确的Redis服务器

### ISSUE THREAD

**Issue by xiaotianhu** [Terry-Mao/gopush-cluster#37]
Message模块配置Redis为不带密码的情况下,会跳转到Messge/redis.go的91行
	log.Error("redis.Dial(\"%s\", \"%s\") error(%v)", tmpProto, tmpAddr, err)
变量tmpProto和tmpAddr都是空

**Comment by xiaotianhu** [comment]
把61行	reg := regexp.MustCompile("(.+)@(.+)#(.+)|(.+)@(.+)")
改为	reg := regexp.MustCompile("(.+)@(.+)")
只匹配不带密码情况的Redis 因为单机使用只监听了127.0.0.1 问题解决

**Comment by Terry-Mao** [comment]
能否提一个patch过来。我直接merge

**Comment by mecaocao** [comment]
@xiaotianhu，的确是因为这个问题搞的
