### ISSUE TITLE
消息的mid算是“版本”的意思吗？

### ISSUE THREAD

**Issue by 879913935** [Terry-Mao/gopush-cluster#39]
我没看到怎么生成的mid,具体哪段代码有具体点的

**Comment by Terry-Mao** [comment]
就是 message id ，逐渐增长的

**Comment by 879913935** [comment]
能给个大致的代码位置吗，没找到

**Comment by 879913935** [comment]
b.Lock()
			defer b.Unlock()
			timeId := id.Get()
			msg := &myrpc.Message{Msg: args.Msg, MsgId: timeId}

是这里吧

**Comment by Terry-Mao** [comment]
对的
