### ISSUE TITLE
comet中的websocket路径出错，源代码路径已经移走

### ISSUE THREAD

**Issue by eric-hon** [Terry-Mao/gopush-cluster#48]
comet中的websocket路径出错，源代码路径已经移走，需更改

**Comment by eric-hon** [comment]
go install
pubsub_websocket.go:21:2: code in directory /data/apps/go/src/github.com/golang/net/websocket expects import "golang.org/x/net/websocket

**Comment by heipacker** [comment]
这个还没有fix吗　为啥最新的还有这个错误提示额
