### ISSUE TITLE
go语言的版本是否有些过老，在新版本下编译不过(go 1.7.3)

### ISSUE THREAD

**Issue by 756445638** [Terry-Mao/gopush-cluster#51]
$ go version
go version go1.7.3 windows/386

$ go install github.com/terry-mao/gopush-cluster/web
# github.com/Terry-Mao/gopush-cluster/zk
..\zk\zk.go:148: undefined: syscall.Kill

希望可以适配golang娇高的版本

**Comment by imaben** [comment]
你用的windows吧
1、放弃windows
2、还是放弃windows吧，虽然注释掉就可以编译过去！

**Comment by imaben** [comment]
信号是linux/unix下的概念

**Comment by 756445638** [comment]
恩 好的，最近有时间把双系统搞一搞
