### ISSUE TITLE
现在不支持公信推送吗？

### ISSUE THREAD

**Issue by CBDlkl** [Terry-Mao/gopush-cluster#55]
* 公信的貌似没有，在源代码里面，也只找到了单条私信推送，和多条私信推送。并没有看到关于公信推送的方法或内容。
* 但是我在js的样例代码里面却看到了公信推送的按钮。
* 请问，是否支持公信推送呢？

**Comment by chigosec** [comment]
同问这个问题，关于文档里面的gid=1的情况，发布消息时候，没有任何的选择

**Comment by li-keli** [comment]
@ch1g0 这是陈年老问题了，推荐使用GoIM项目，不要用gopush这个项目了。

https://github.com/Terry-Mao/goim/blob/master/README_cn.md#%E5%AE%89%E8%A3%85
